FROM mcr.microsoft.com/devcontainers/go

# Install Python
# RUN apt-get update && apt-get install -y python3 python3-pip

# Upgrade pip to the latest version
# RUN pip3 install --upgrade pip

# Add your Python packages installation here, if needed
# RUN pip install package_name
